name: Post JSON File to Two URLs
on:
 push:
  branches:
   - main # Runs only when pushing to the main branch
 workflow_dispatch: # Allows manual trigger
 
jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:XFDdqCsGRyq4KELUx_Qi5Q@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:bp_vbLoURLixFUjO6EDnnQ/streams/AQAAAKEOOLaNEURArOA76TRYPmkAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json
      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:8sXivUoXRuS3QyXU3v7fSg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:bp_vbLoURLixFUjO6EDnnQ/streams/AQAAABrcQlOvZU2km0EiVhRfJSUAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json
      - name: Send JSON Data to Third URL
        run: |
          curl -X POST "https://:oqkm9YglTf6X2CWGiINL_A@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:bp_vbLoURLixFUjO6EDnnQ/streams/AQAAAB-RlbrV1U2LmXZsEe8a6rYAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json       
